Python 2.6.6 (r266:84292, Sep 15 2010, 16:22:56) 
[GCC 4.4.5] on linux2
Type "copyright", "credits" or "license()" for more information.

    ****************************************************************
    Personal firewall software may warn about the connection IDLE
    makes to its subprocess using this computer's internal loopback
    interface.  This connection is not visible on any external
    interface and no data is sent to or received from the Internet.
    ****************************************************************
    
IDLE 2.6.6      ==== No Subprocess ====
>>> 
Finding gcd( 1656 , -5083 )...
Finding, x, y such that gcd(1656,-5083) =1656x + -5083y.
                       x, y = 1 0
1656 = 0 * -5083 + 1656 , x, y = 1 0
-5083 = -4 * 1656 + 1541 , x, y = 4 1
1656 = 1 * 1541 + 115 , x, y = -3 -1
1541 = 13 * 115 + 46 , x, y = 43 14
115 = 2 * 46 + 23 , x, y = -89 -29
By the Extended Euclidean Algorithm, gcd(1656,-5083) = 23
gcd(1656,-5083) can be written as -89*1656 + -29*-5083
>>> 
Finding gcd( 1656 , -5083 )...
Finding, x, y such that gcd(1656,-5083) =1656x + -5083y.
                       x, y = 1 0
1656 = 0 * -5083 + 1656 , x, y = 1 0
-5083 = -4 * 1656 + 1541 , x, y = 4 1
1656 = 1 * 1541 + 115 , x, y = -3 -1
1541 = 13 * 115 + 46 , x, y = 43 14
115 = 2 * 46 + 23 , x, y = -89 -29
By the Extended Euclidean Algorithm, gcd(1656,-5083) = 23
gcd(1656,-5083) can be written as -89*1656 + -29*-5083
>>> 
(1, 3, -4)
>>> 
Finding gcd( 1656 , -5083 )...
Finding, x, y such that gcd(1656,-5083) =1656x + -5083y.
                       x, y = 1 0
1656 = 0 * -5083 + 1656 , x, y = 1 0
-5083 = -4 * 1656 + 1541 , x, y = 4 1
1656 = 1 * 1541 + 115 , x, y = -3 -1
1541 = 13 * 115 + 46 , x, y = 43 14
115 = 2 * 46 + 23 , x, y = -89 -29
By the Extended Euclidean Algorithm, gcd(1656,-5083) = 23
gcd(1656,-5083) can be written as -89*1656 + -29*-5083
>>> 
(1, 3, -4)
>>> 
Traceback (most recent call last):
  File "/home/evgeny/Programming/zzzzzz.py", line 3, in <module>
    print eea(56,75,e=1,l=1)
TypeError: eea() got an unexpected keyword argument 'l'
>>> 
Traceback (most recent call last):
  File "/home/evgeny/Programming/zzzzzz.py", line 3, in <module>
    print eea(56,75,e=1,l=1)
TypeError: eea() got an unexpected keyword argument 'l'
>>> 
Traceback (most recent call last):
  File "/home/evgeny/Programming/zzzzzz.py", line 3, in <module>
    print eea(56,75,e=1,l=1)
TypeError: eea() got an unexpected keyword argument 'l'
>>> 
Traceback (most recent call last):
  File "/home/evgeny/Programming/zzzzzz.py", line 3, in <module>
    print eea(56,75,e=1,v=0,l=1)
TypeError: eea() got an unexpected keyword argument 'l'
>>> 
Traceback (most recent call last):
  File "/home/evgeny/Programming/zzzzzz.py", line 3, in <module>
    print eea(56,75,e=1,v=0,l=1)
TypeError: eea() got an unexpected keyword argument 'l'
>>> 
(1, 3, -4)
>>> 
(1, 3, -4)
>>> from ExtendedEuclideanAlgorithm import eea; print eea(235,6334,e=1)
